//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Tools.Belt.Common.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Tools.Belt.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Description
        ///29/03/2002,Good Friday
        ///01/01/2002,New Years Day
        ///01/04/2002,Easter Monday
        ///03/06/2002,Spring Bank Holiday
        ///26/08/2002,Late Summer Holiday
        ///25/12/2002,Christmas Day
        ///26/12/2002,Boxing Day
        ///04/06/2002,Jubilee Holiday
        ///06/05/2002,May Day
        ///01/01/2003,New Years Day
        ///18/04/2003,Good Friday
        ///21/04/2003,Easter Monday
        ///05/05/2003,Early May Bank Holiday
        ///26/05/2003,Spring Bank Holiday
        ///25/08/2003,Summer Bank Holiday
        ///25/12/2003,Christmas Day
        ///26/12/2003,Boxing Day
        ///01/01/2004,New Years Day
        ///09/04/2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublicHolidays {
            get {
                return ResourceManager.GetString("PublicHolidays", resourceCulture);
            }
        }
    }
}
